dotnet_mvc/KiemTraGiuaKy/ThiGK64CNTT3_64132989_De1/ThiGK64CNTT3_64132989_De1/Controllers/ThanhViens64132989Controller.cs
using System;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using ThiGK64CNTT3_64132989_De1.Models;

namespace ThiGK64CNTT3_64132989_De1.Controllers
{
    public class ThanhViens64132989Controller : Controller
    {
        private Model_64132989 db = new Model_64132989();

        // GET: ThanhViens64132989
        public ActionResult Index(int page = 1, int pageSize = 2)
        {
            var thanhViens = db.ThanhViens.Include(t => t.Tinh)
                                          .OrderBy(t => t.MaTV)
                                          .Skip((page - 1) * pageSize)
                                          .Take(pageSize)
                                          .ToList();

            ViewBag.TotalItems = db.ThanhViens.Count();
            ViewBag.Page = page;
            ViewBag.PageSize = pageSize;
            return View(thanhViens);
        }

        // GET: ThanhViens64132989/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThanhVien thanhVien = db.ThanhViens.Find(id);
            if (thanhVien == null)
            {
                return HttpNotFound();
            }
            return View(thanhVien);
        }

        // GET: ThanhViens64132989/Create
        public ActionResult Create()
        {
            ViewBag.MaTinh = new SelectList(db.Tinhs, "MaTinh", "TenTinh");
            return View();
        }

        // POST: ThanhViens64132989/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaTV,HoTV,TenTV,NgaySinh,GioiTinh,Email,DiaChi,MaTinh")] ThanhVien thanhVien, HttpPostedFileBase AnhDaiDien)
        {
            if (ModelState.IsValid)
            {
                if (AnhDaiDien != null && AnhDaiDien.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(AnhDaiDien.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                    AnhDaiDien.SaveAs(path);
                    thanhVien.AnhDaiDien = fileName;  // Lưu tên tệp ảnh vào thuộc tính AnhDaiDien
                }

                db.ThanhViens.Add(thanhVien);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaTinh = new SelectList(db.Tinhs, "MaTinh", "TenTinh", thanhVien.MaTinh);
            return View(thanhVien);
        }

        [HttpGet]
        public ActionResult TimKiemTV_64132989(string HoTen, int? MaTinh, int page = 1, int pageSize = 2)
        {
            // Viết truy vấn SQL với tìm kiếm không dấu bằng COLLATE
            var sql = @"
                SELECT * 
                FROM ThanhVien
                WHERE (@MaTinh IS NULL OR MaTinh = @MaTinh)
                AND (@HoTen IS NULL OR (HoTV + ' ' + TenTV) COLLATE SQL_Latin1_General_CP1_CI_AI LIKE '%' + @HoTen + '%')
                ORDER BY MaTV
                OFFSET @Offset ROWS
                FETCH NEXT @PageSize ROWS ONLY;";

            // Tính toán giá trị Offset dựa trên số trang và số bản ghi mỗi trang
            int offset = (page - 1) * pageSize;

            // Tham số cho truy vấn dữ liệu
            var dataParameters = new[]
            {
        new SqlParameter("@MaTinh", MaTinh.HasValue ? (object)MaTinh.Value : DBNull.Value),
        new SqlParameter("@HoTen", string.IsNullOrEmpty(HoTen) ? (object)DBNull.Value : HoTen),
        new SqlParameter("@Offset", offset),
        new SqlParameter("@PageSize", pageSize)
    };

            // Thực hiện truy vấn lấy dữ liệu
            var thanhViens = db.Database.SqlQuery<ThanhVien>(sql, dataParameters).ToList();

            // Truy vấn đếm tổng số bản ghi sau khi lọc
            var countSql = @"
                SELECT COUNT(*)
                FROM ThanhVien
                WHERE (@MaTinh IS NULL OR MaTinh = @MaTinh)
                AND (@HoTen IS NULL OR (HoTV + ' ' + TenTV) COLLATE SQL_Latin1_General_CP1_CI_AI LIKE '%' + @HoTen + '%');";

            // Tham số cho truy vấn đếm
            var countParameters = new[]
            {
                new SqlParameter("@MaTinh", MaTinh.HasValue ? (object)MaTinh.Value : DBNull.Value),
                new SqlParameter("@HoTen", string.IsNullOrEmpty(HoTen) ? (object)DBNull.Value : HoTen)
            };

            // Thực hiện truy vấn đếm
            int totalItems = db.Database.SqlQuery<int>(countSql, countParameters).Single();

            // Gán thông tin phân trang vào ViewBag
            ViewBag.TotalItems = totalItems;
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            ViewBag.HoTen = HoTen;
            ViewBag.MaTinh = new SelectList(db.Tinhs, "MaTinh", "TenTinh", MaTinh);

            return View(thanhViens);
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

dotnet_mvc/KiemTraGiuaKy/ThiGK64CNTT3_64132989_De1/ThiGK64CNTT3_64132989_De1/Views/ThanhViens64132989/Create.cshtml
@model ThiGK64CNTT3_64132989_De1.Models.ThanhVien

@{
    ViewBag.Title = "Thêm thành viên mới";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="display-6">Thêm thành viên mới</h2>
<div>
    @Html.ActionLink("Về trang danh sách", "Index", null, new { @class = "btn btn-outline-secondary mt-2" })
</div>

@using (Html.BeginForm("Create", "ThanhViens64132989", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="col-md-10 mt-5">
        @Html.LabelFor(model => model.MaTV, htmlAttributes: new { @class = "form-label col-md-2" })
        @Html.EditorFor(model => model.MaTV, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập mã thành viên" } })
        @Html.ValidationMessageFor(model => model.MaTV, "", new { @class = "text-danger" })
    </div>

    <div class="col-md-10 mt-3">
        @Html.LabelFor(model => model.HoTV, htmlAttributes: new { @class = "form-label col-md-2" })
        @Html.EditorFor(model => model.HoTV, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập họ thành viên" } })
        @Html.ValidationMessageFor(model => model.HoTV, "", new { @class = "text-danger" })
    </div>

    <div class="col-md-10 mt-3">
        @Html.LabelFor(model => model.TenTV, htmlAttributes: new { @class = "form-label col-md-2" })
        @Html.EditorFor(model => model.TenTV, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập tên thành viên" } })
        @Html.ValidationMessageFor(model => model.TenTV, "", new { @class = "text-danger" })
    </div>

    <div class="col-md-10 mt-3">
        @Html.LabelFor(model => model.AnhDaiDien, htmlAttributes: new { @class = "form-label col-md-2" })
        @Html.EditorFor(model => model.AnhDaiDien, new { htmlAttributes = new { @class = "form-control", @type = "file", @name = "AnhDaiDien" } })
        @Html.ValidationMessageFor(model => model.AnhDaiDien, "", new { @class = "text-danger" })
    </div>

    <div class="col-md-10 mt-3">
        @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "form-label col-md-2" })
        @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control", type = "date" } })
        @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
    </div>

    <div class="col-md-10 mt-3">
        @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "form-label col-md-2" })
        <div class="form-check form-check-inline">
            @Html.RadioButtonFor(model => model.GioiTinh, true, new { @class = "form-check-input", id = "gioiTinhNam" })
            <label class="form-check-label" for="gioiTinhNam">Nam</label>
        </div>
        <div class="form-check form-check-inline">
            @Html.RadioButtonFor(model => model.GioiTinh, false, new { @class = "form-check-input", id = "gioiTinhNu" })
            <label class="form-check-label" for="gioiTinhNu">Nữ</label>
        </div>
        @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
    </div>

    <div class="col-md-10 mt-3">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "form-label col-md-2" })
        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập email" } })
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
    </div>

    <div class="col-md-10 mt-3">
        @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "form-label col-md-2" })
        @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập địa chỉ" } })
        @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
    </div>

    <div class="col-md-10 mt-3">
        @Html.LabelFor(model => model.MaTinh, "Tỉnh/Thành phố", htmlAttributes: new { @class = "form-label col-md-2" })
        @Html.DropDownListFor(model => model.MaTinh, ViewBag.MaTinh as SelectList, "Chọn tỉnh/thành phố", new { @class = "form-select" })
        @Html.ValidationMessageFor(model => model.MaTinh, "", new { @class = "text-danger" })
    </div>

    <div class="col-md-offset-2 col-md-10 mt-5">
        <input type="submit" value="Lưu thông tin" class="btn btn-primary" />
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

dotnet_mvc/KiemTraGiuaKy/ThiGK64CNTT3_64132989_De1/ThiGK64CNTT3_64132989_De1/Views/ThanhViens64132989/Details.cshtml
@model ThiGK64CNTT3_64132989_De1.Models.ThanhVien

@{
    ViewBag.Title = "Chi tiết thành viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="display-6">Thông tin thành viên</h2>

<div>
    @Html.ActionLink("Về trang danh sách", "Index", null, new { @class = "btn btn-outline-secondary mt-2 mb-4" })
</div>

<div class="card shadow-sm card-body d-flex">
    <div class="d-flex flex-row align-items-start mb-3">
        <div class="me-3 pe-4">
            @if (!string.IsNullOrEmpty(Model.AnhDaiDien))
            {
                <img src="~/Images/@Model.AnhDaiDien" alt="Ảnh đại diện" class="rounded" style="max-width: 300px;" />
            }
            else
            {
                <p>Không có ảnh</p>
            }
        </div>
        <div>
            <dl class="row">
                <dt class="col-sm-4">Tên tỉnh</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.Tinh.TenTinh)</dd>

                <dt class="col-sm-4">Họ thành viên</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.HoTV)</dd>

                <dt class="col-sm-4">Tên thành viên</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.TenTV)</dd>

                <dt class="col-sm-4">Ngày sinh</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.NgaySinh)</dd>

                <dt class="col-sm-4">Giới tính</dt>
                <dd class="col-sm-8">@(Model.GioiTinh ? "Nam" : "Nữ")</dd>

                <dt class="col-sm-4">Email</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.Email)</dd>

                <dt class="col-sm-4">Địa chỉ</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.DiaChi)</dd>
            </dl>
        </div>
    </div>
</div>

dotnet_mvc/KiemTraGiuaKy/ThiGK64CNTT3_64132989_De1/ThiGK64CNTT3_64132989_De1/Views/ThanhViens64132989/Index.cshtml
@model IEnumerable<ThiGK64CNTT3_64132989_De1.Models.ThanhVien>

@{
    ViewBag.Title = "Danh sách thành viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int totalPages = (int)Math.Ceiling((double)ViewBag.TotalItems / ViewBag.PageSize);
}

<h3 class="display-6 mb-3">Danh sách thành viên</h3>

<p>
    @Html.ActionLink("Thêm thành viên mới", "Create", null, new { @class = "btn btn-primary" })
</p>

<table class="table">
    <tr>
        <th>STT</th>
        <th>@Html.DisplayNameFor(model => model.MaTV)</th>
        <th>@Html.DisplayNameFor(model => model.HoTV)</th>
        <th>@Html.DisplayNameFor(model => model.TenTV)</th>
        <th>@Html.DisplayNameFor(model => model.AnhDaiDien)</th>
        <th>@Html.DisplayNameFor(model => model.NgaySinh)</th>
        <th>@Html.DisplayNameFor(model => model.GioiTinh)</th>
        <th>@Html.DisplayNameFor(model => model.Email)</th>
        <th>@Html.DisplayNameFor(model => model.DiaChi)</th>
        <th>@Html.DisplayNameFor(model => model.Tinh.TenTinh)</th>
        <th></th>
    </tr>

    @{ int i = (ViewBag.Page - 1) * ViewBag.PageSize + 1; }
    @foreach (var item in Model)
    {
        <tr>
            <td>@(i++)</td>
            <td>@Html.DisplayFor(modelItem => item.MaTV)</td>
            <td>@Html.DisplayFor(modelItem => item.HoTV)</td>
            <td>@Html.DisplayFor(modelItem => item.TenTV)</td>
            <td>@Html.DisplayFor(modelItem => item.AnhDaiDien)</td>
            <td>@Html.DisplayFor(modelItem => item.NgaySinh)</td>
            <td>@(item.GioiTinh ? "Nam" : "Nữ")</td>
            <td>@Html.DisplayFor(modelItem => item.Email)</td>
            <td>@Html.DisplayFor(modelItem => item.DiaChi)</td>
            <td>@Html.DisplayFor(modelItem => item.Tinh.TenTinh)</td>
            <td>@Html.ActionLink("Xem chi tiết", "Details", new { id = item.MaTV })</td>
        </tr>
    }
</table>

<!-- Pagination Controls -->
<nav aria-label="Page navigation">
    <ul class="pagination">
        @if (ViewBag.Page > 1)
        {
            <li class="page-item">
                <a class="page-link" href="@Url.Action("Index", new { page = ViewBag.Page - 1 })">Previous</a>
            </li>
        }
        @for (int pageNum = 1; pageNum <= totalPages; pageNum++)
        {
            <li class="page-item @(pageNum == ViewBag.Page ? "active" : "")">
                <a class="page-link" href="@Url.Action("Index", new { page = pageNum })">@pageNum</a>
            </li>
        }
        @if (ViewBag.Page < totalPages)
        {
            <li class="page-item">
                <a class="page-link" href="@Url.Action("Index", new { page = ViewBag.Page + 1 })">Next</a>
            </li>
        }
    </ul>
</nav>

dotnet_mvc/KiemTraGiuaKy/ThiGK64CNTT3_64132989_De1/ThiGK64CNTT3_64132989_De1/Views/ThanhViens64132989/TimKiemTV_64132989.cshtml
@model IEnumerable<ThiGK64CNTT3_64132989_De1.Models.ThanhVien>

@{
    ViewBag.Title = "Tìm kiếm thành viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int totalPages = (int)Math.Ceiling((double)ViewBag.TotalItems / ViewBag.PageSize);
}

<h3 class="display-6 mb-3">Tìm kiếm thành viên</h3>

<p>
    @Html.ActionLink("Về trang danh sách", "Index", "ThanhViens64132989", null, new { @class = "btn btn-primary" })
</p>

@using (Html.BeginForm("TimKiemTV_64132989", "ThanhViens64132989", FormMethod.Get))
{
    @Html.AntiForgeryToken()

    <div class="mb-3 w-50">
        <label for="HoTen" class="form-label">Tên thành viên</label>
        <input type="text" class="form-control" id="HoTen" name="HoTen" placeholder="Nhập tên thành viên"
               value="@ViewBag.HoTen" />
    </div>

    <div class="mb-3 w-50">
        <label for="MaTinh" class="form-label">Tỉnh</label>
        @Html.DropDownList("MaTinh", ViewBag.MaTinh as SelectList, "Chọn tỉnh", new { @class = "form-select" })
    </div>

    <div class="mt-3 mb-5">
        <button class="btn btn-outline-secondary me-3" type="submit">Tìm kiếm</button>
        @Html.ActionLink("Nhập mới", "TimKiemTV_64132989", null, new { @class = "btn btn-primary" })
    </div>
}

@if (!Model.Any())
{
    <div class="alert alert-warning" role="alert">
        Không có kết quả nào được tìm thấy.
    </div>
}
else
{
    <table class="table">
        <tr>
            <th>STT</th>
            <th>@Html.DisplayNameFor(model => model.MaTV)</th>
            <th>@Html.DisplayNameFor(model => model.HoTV)</th>
            <th>@Html.DisplayNameFor(model => model.TenTV)</th>
            <th>@Html.DisplayNameFor(model => model.NgaySinh)</th>
            <th>@Html.DisplayNameFor(model => model.GioiTinh)</th>
            <th>@Html.DisplayNameFor(model => model.Email)</th>
            <th>@Html.DisplayNameFor(model => model.DiaChi)</th>
            <th>@Html.DisplayNameFor(model => model.Tinh.TenTinh)</th>
            <th></th>
        </tr>

        @{ int i = (ViewBag.Page - 1) * ViewBag.PageSize + 1; }
        @foreach (var item in Model)
        {
            <tr>
                <td>@(i++)</td>
                <td>@Html.DisplayFor(modelItem => item.MaTV)</td>
                <td>@Html.DisplayFor(modelItem => item.HoTV)</td>
                <td>@Html.DisplayFor(modelItem => item.TenTV)</td>
                <td>@Html.DisplayFor(modelItem => item.NgaySinh)</td>
                <td>@(item.GioiTinh ? "Nam" : "Nữ")</td>
                <td>@Html.DisplayFor(modelItem => item.Email)</td>
                <td>@Html.DisplayFor(modelItem => item.DiaChi)</td>
                <td>@Html.DisplayFor(modelItem => item.Tinh.TenTinh)</td>
                <td>@Html.ActionLink("Xem chi tiết", "Details", new { id = item.MaTV })</td>
            </tr>
        }
    </table>
}

<!-- Pagination Controls -->
<nav aria-label="Page navigation">
    <ul class="pagination">
        @if (ViewBag.Page > 1)
        {
            <li class="page-item">
                <a class="page-link" href="@Url.Action("TimKiemTV_64132989", new { page = ViewBag.Page - 1, HoTen = ViewBag.HoTen, MaTinh = Request.QueryString["MaTinh"] })">Previous</a>
            </li>
        }
        @for (int pageNum = 1; pageNum <= totalPages; pageNum++)
        {
            <li class="page-item @(pageNum == ViewBag.Page ? "active" : "")">
                <a class="page-link" href="@Url.Action("TimKiemTV_64132989", new { page = pageNum, HoTen = ViewBag.HoTen, MaTinh = Request.QueryString["MaTinh"] })">@pageNum</a>
            </li>
        }
        @if (ViewBag.Page < totalPages)
        {
            <li class="page-item">
                <a class="page-link" href="@Url.Action("TimKiemTV_64132989", new { page = ViewBag.Page + 1, HoTen = ViewBag.HoTen, MaTinh = Request.QueryString["MaTinh"] })">Next</a>
            </li>
        }
    </ul>
</nav>